/*-----------------------------------------------------------------------------------------------------------------------|
| This file was generated by mini-mbm CMake when the Xcode project was first configured.                                |
| It belongs to YOUR game project — edit it freely.                                                                      |
|                                                                                                                        |
| CMake will NOT overwrite this file once it exists in your game folder.                                                 |
| The engine template lives at platform-ios/my-commands.swift (never modified by CMake).                                 |
|-----------------------------------------------------------------------------------------------------------------------*/

import UIKit

/// Game-specific native iOS command handler.
///
/// Add your custom native iOS commands here.  They are invoked from Lua via:
///
///     mbm.doCommands("myCommand", "someParam")
///
/// Return `true` if your handler processed the command, `false` to let the
/// engine log a warning.
///
/// ## Synchronous commands
/// Write the result into the `result` buffer (max `maxSize` bytes, NUL-terminated)
/// and return `true`.  The value is returned directly to Lua:
///
///     local value = mbm.doCommands("myCommand", "param")
///
/// ## Async commands
/// Start a UIKit operation (e.g. present a view controller), return `true`
/// immediately, and when the operation finishes call:
///
///     mbm_ios_onCallBackCommands("myCommand", resultString)
///
/// Then define a matching Lua global function:
///
///     function myCommand(result) print(result) end
///
@objc public class MyCommands: NSObject, MbmCommandsProtocol {

    @objc public func handleCommand(
        _ command: String,
        param: String,
        result: UnsafeMutablePointer<CChar>,
        maxSize: Int32
    ) -> Bool {
        // ── Add your custom native iOS commands below ─────────────────────────
        //
        // switch command {
        // case "myCommand":
        //     // synchronous example — fill result and return true
        //     let value = "hello from native"
        //     let bytes = Array(value.utf8.prefix(Int(maxSize) - 1))
        //     for (i, b) in bytes.enumerated() { result[i] = CChar(bitPattern: b) }
        //     result[bytes.count] = 0
        //     return true
        //
        // case "myAsyncCommand":
        //     // async example — return immediately, callback fires later
        //     DispatchQueue.main.async {
        //         // ... do something ...
        //         mbm_ios_onCallBackCommands("myAsyncCommand", "done")
        //     }
        //     return true
        //
        // default:
        //     break
        // }

        return false
    }
}
